server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/socialmedia?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
